# Generated by Django 4.1.7 on 2023-03-18 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_bid_listing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bid',
            options={'ordering': ['-bid_price']},
        ),
    ]
